### ISSUE TITLE
install.sh bugs

### ISSUE THREAD

**Issue by Rahix** [Dean4Devil/dotfiles#1] opened 2015-05-16 10:13 UTC
I recently tried to use your config, but I came along the problem, that YCM is downloaded, but not installed. Also The $RUST_SRC_PATH in the .vimrc is set to your local one @Dean4Devil.

**Comment by Dean4Devil** [comment] 2015-05-16 10:19
Closed as 'Not a bug'
YCM will always stay manual since I want more control over what features it contains. For installation instructions have a look at YCMs manual.
The rust src path is set to what I always use.
If you don't want to bother with those two, check out the nocompletion branch.

**Closed by Dean4Devil** 2015-05-16 10:19 UTC
